# Generated by Django 2.0.4 on 2018-04-12 07:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=14)),
                ('guest_name', models.CharField(blank=True, max_length=512, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Мужской'), ('female', 'Женский')], max_length=10)),
                ('birth_year', models.CharField(blank=True, max_length=4)),
                ('position', models.CharField(blank=True, max_length=128)),
                ('chekin', models.DateTimeField(blank=True, null=True)),
                ('chekout', models.DateTimeField(blank=True, null=True)),
                ('type_placement', models.CharField(blank=True, choices=[('room', 'Номер'), ('prim_room', 'Место (основное)'), ('second_room', 'Место (дополнительное)')], max_length=10)),
                ('status', models.CharField(blank=True, choices=[('active', 'Проживает'), ('reserve', 'Бронь'), ('resident', 'Постоянно проживающий'), ('timeresident', 'Вахтовый работник'), ('cancel', 'Отмена')], max_length=50)),
                ('payment', models.CharField(blank=True, choices=[('withoutpay', 'Без оплаты'), ('cash', 'Наличная'), ('nocash', 'Безналичная')], max_length=50)),
                ('description', models.TextField(blank=True, max_length=512)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
            ],
            options={
                'permissions': (('cm_read_booking_history', 'Просмотр истории изменений таблицы размещения гостей в номерах'),),
                'verbose_name_plural': 'Размещения',
                'verbose_name': 'Размещение',
            },
        ),
        migrations.CreateModel(
            name='CategoryRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=512)),
                ('tarif', models.PositiveIntegerField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Категории номеров',
                'verbose_name': 'Категория номера',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Мероприятия',
                'verbose_name': 'Мероприятие',
            },
        ),
        migrations.CreateModel(
            name='Filial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Филиалы',
                'verbose_name': 'Филиал',
            },
        ),
        migrations.CreateModel(
            name='HistoricalBooking',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=14)),
                ('guest_name', models.CharField(blank=True, max_length=512, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Мужской'), ('female', 'Женский')], max_length=10)),
                ('birth_year', models.CharField(blank=True, max_length=4)),
                ('position', models.CharField(blank=True, max_length=128)),
                ('chekin', models.DateTimeField(blank=True, null=True)),
                ('chekout', models.DateTimeField(blank=True, null=True)),
                ('type_placement', models.CharField(blank=True, choices=[('room', 'Номер'), ('prim_room', 'Место (основное)'), ('second_room', 'Место (дополнительное)')], max_length=10)),
                ('status', models.CharField(blank=True, choices=[('active', 'Проживает'), ('reserve', 'Бронь'), ('resident', 'Постоянно проживающий'), ('timeresident', 'Вахтовый работник'), ('cancel', 'Отмена')], max_length=50)),
                ('payment', models.CharField(blank=True, choices=[('withoutpay', 'Без оплаты'), ('cash', 'Наличная'), ('nocash', 'Безналичная')], max_length=50)),
                ('description', models.TextField(blank=True, max_length=512)),
                ('created', models.DateTimeField(blank=True, editable=False)),
                ('updated', models.DateTimeField(blank=True, editable=False)),
                ('deleted', models.BooleanField(default=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('event', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='hotelapp.Event')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
                'verbose_name': 'historical Размещение',
            },
        ),
        migrations.CreateModel(
            name='HistoricalHotel',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=512)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=512)),
                ('manager', models.CharField(blank=True, max_length=128)),
                ('phone', models.CharField(blank=True, max_length=128)),
                ('description', models.TextField(blank=True, max_length=1024)),
                ('created', models.DateTimeField(blank=True, editable=False)),
                ('updated', models.DateTimeField(blank=True, editable=False)),
                ('deleted', models.BooleanField(default=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('filial', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='hotelapp.Filial')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
                'verbose_name': 'historical Объект размещения',
            },
        ),
        migrations.CreateModel(
            name='HistoricalRoom',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('room_number', models.CharField(max_length=8)),
                ('primary_place', models.PositiveSmallIntegerField()),
                ('secondary_place', models.PositiveSmallIntegerField()),
                ('description', models.TextField(blank=True, max_length=1024)),
                ('created', models.DateTimeField(blank=True, editable=False)),
                ('updated', models.DateTimeField(blank=True, editable=False)),
                ('deleted', models.BooleanField(default=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('category_room', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='hotelapp.CategoryRoom')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
                'verbose_name': 'historical Номер',
            },
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, unique=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('address', models.CharField(blank=True, max_length=512)),
                ('manager', models.CharField(blank=True, max_length=128)),
                ('phone', models.CharField(blank=True, max_length=128)),
                ('description', models.TextField(blank=True, max_length=1024)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('filial', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hotelapp.Filial')),
            ],
            options={
                'permissions': (('cm_read_hotel_history', 'Просмотр истории изменений справочника Объекты размещения'),),
                'verbose_name_plural': 'Объекты размещения',
                'verbose_name': 'Объект размещения',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Регионы',
                'verbose_name': 'Регион',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=8)),
                ('primary_place', models.PositiveSmallIntegerField()),
                ('secondary_place', models.PositiveSmallIntegerField()),
                ('description', models.TextField(blank=True, max_length=1024)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('category_room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='hotelapp.CategoryRoom')),
                ('hotel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='hotelapp.Hotel')),
            ],
            options={
                'permissions': (('cm_read_room_history', 'Просмотр истории изменений справочника номеров'),),
                'verbose_name_plural': 'Номера',
                'verbose_name': 'Номер',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='hotelapp.Filial')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Профили пользователя',
                'verbose_name': 'Профиль пользователя',
            },
        ),
        migrations.AddField(
            model_name='historicalroom',
            name='hotel',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='hotelapp.Hotel'),
        ),
        migrations.AddField(
            model_name='historicalbooking',
            name='room',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='hotelapp.Room'),
        ),
        migrations.AddField(
            model_name='filial',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hotelapp.Region'),
        ),
        migrations.AddField(
            model_name='categoryroom',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hotelapp.Region'),
        ),
        migrations.AddField(
            model_name='booking',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='hotelapp.Event'),
        ),
        migrations.AddField(
            model_name='booking',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hotelapp.Room'),
        ),
    ]
