# Generated by Django 2.0.4 on 2018-04-14 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapp', '0002_auto_20180412_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='chekin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='chekout',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='code',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='historicalbooking',
            name='chekin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalbooking',
            name='chekout',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalbooking',
            name='code',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
